queue_rules:
  - name: default
    merge_conditions:
      - check-success=placeholder-check
pull_request_rules:
  - name: queue-all
    conditions:
      - base=main
    actions:
      queue:
        name: default
